name: terminal_control_mobile
version: 1.0.0+1
publish_to: "none"
description: App Flutter para celular em pé enviar comandos via WebSocket ao Raspberry PinPad Bridge.

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
